name: Detect Stale

on:
  schedule:
    - cron:  '0 0 1,15 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Detect Stale
        run: |
          STALE_TAGS=$(curl 'https://hub.docker.com/v2/repositories/jayrepo/nodejs-chrome/tags/?page_size=10000' | jq -r '.results[] | select(.tag_status == "inactive").name')
          for i in ${STALE_TAGS}; do docker pull "jayrepo/nodejs-chrome:${i}"; docker image prune -f -a; done
