name: CI

on:
  schedule:
    - cron:  '12 0 * * *'

  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    container: node:current
    outputs:
      version: ${{ steps.ver.outputs.version }}
      shortVersion: ${{ steps.ver.outputs.shortVersion }}
      exitCode: ${{ steps.comp.outputs.exitCode }}
    
    steps:
      - name: Version
        id: ver
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          apt-get update -qqy
          apt-get -qqy install jq

          CHROME_VERSION=$(apt-cache show google-chrome-stable | grep Version | awk '{print $2}' | cut -d '-' -f 1)
          NODE_VERSION=$(node -v | sed -E "s/v([0-9.]+)/\1/")

          VERSION="${NODE_VERSION}-${CHROME_VERSION}"
          echo $VERSION

          SHORT_VERSION="${NODE_VERSION%%.*}-${CHROME_VERSION%%.*}"
          echo $SHORT_VERSION
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "shortVersion=${SHORT_VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compare
        id: comp
        shell: bash
        run: |
          if [[ $(< version) == "${{steps.ver.outputs.version}}" ]]; then
              echo "same version"
              echo "exitCode=1" >> $GITHUB_OUTPUT
              exit 1
          fi
          echo echo "exitCode=0" >> $GITHUB_OUTPUT

          
  build:
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.exitCode == '0'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            jayrepo/nodejs-chrome:latest
            jayrepo/nodejs-chrome:${{ needs.version.outputs.version }}
            jayrepo/nodejs-chrome:${{ needs.version.outputs.shortVersion }}
          
